name: NPR Podcasts (Legacy)
description: NPR Podcasts (Legacy Editions)


github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

theme: jekyll-theme-cayman
